### ISSUE TITLE
Automating initialisation of baremetal for self-hosted-runners

### ISSUE THREAD

**Issue by hershd23** [layer5io/meshery-smp-action#38]
### Current Behavior

Currently we are 

1. Doing baremetal initialisation manually by going to the equinix UI.
2. Doing the setup by manually SSHing and creating users, installing dependencies etc.

The instructions are mentioned [here](https://docs.google.com/document/d/16b-cWkyhDwumK8afd0YiQtZUe2zc5TfQ_9g7dQ9q8jQ/edit?disco=AAAAVjcwaoU)

### Desired Behavior

Ideally both these tasks should be automated, using the equinix APIs and tools like terraform

### Implementation

We can use tools like terraform and use existing terraform support for equinix APIs to achieve this.
[https://github.com/equinix/terraform-provider-equinix](https://www.google.com/url?q=https://github.com/equinix/terraform-provider-equinix&sa=D&source=docs&ust=1644860017468068&usg=AOvVaw2txjWO6pY9S9ctdgIbxoUx)
[https://github.com/equinix/cloud-provider-equinix-metal](https://www.google.com/url?q=https://github.com/equinix/cloud-provider-equinix-metal&sa=D&source=docs&ust=1644860017468184&usg=AOvVaw3wVsyok92Og-PuLH8T2BPs)
https://github.com/machulav/ec2-github-runner#example

### Acceptance Tests

Successful action runs with complete automation would solve this issue

### Additional Comments
@leecalcote @gyohuangxin would creating a runner on demand (i.e. after starting a workflow) mean that the self-hosted-runner in itself would not be needed? Given we have to register a self-hosted-runner to a repository first.
https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**

**Comment by gyohuangxin** [comment]
Thank you for open this issue @hershd23 

> @leecalcote @gyohuangxin would creating a runner on demand (i.e. after starting a workflow) mean that the self-hosted-runner in itself would not be needed? Given we have to register a self-hosted-runner to a repository first.

I think it's not exactly correct. If we follow this way: https://github.com/machulav/ec2-github-runner#example.  It uses a github-runner to create a self-hosted runner on demand, but we still need to register this self-hosted runner to github repository to receive the job from our github action. It can be implemented with self-hosted REST API: https://docs.github.com/en/rest/reference/actions#self-hosted-runners

Therefore, in my opinion, our example of benchmark workflow on self-hosted runner will look like below:
```
name: Configurable Benchmark Test
on: 
  workflow_dispatch:
    inputs:
      profile_name:
        description: "performance profile to use"
        required: false
      profile_filename:
        description: "test configuration file"
        required: false
      service_mesh:
        type: choice
        required: false
        description: "service mesh being tested"
        options:
          - istio
          - linkerd
      load_generator:
        type: choice
        required: false
        description: "load generator to run tests with"
        options:
          - fortio
          - wrk2
          - nighthawk
          
jobs:
  start-runner:
    name: Start self-hosted CNCF CIL runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-cil-runner.outputs.label }}
      cil-instance-id: ${{ steps.start-cil-runner.outputs.cil-instance-id }}
    steps:
      - name: Configure CNCF CIL credentials
        ......
      - name: Start CNCF CIL runner
        id: start-cil-runner
        uses: layer5io/meshery-smp-action
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          cil-image-id: ubuntu-20.04
          cil-instance-type: c3.small.x86
          user-data-scripts: ....
          ......
  register-runner:
  	name: Register the self-hosted runner to github repo
  	runs-on: ubuntu-latest
  	steps: 
  	......
  run-benchmarks:
    name: Run the configurable benchmarks on the runner
    needs: 
      - start-runner # required to start the main job when the runner is ready
      - register-runner # required to register-runner
    runs-on: ${{ needs.start-runner.outputs.label }} # run the job on the newly created runner
    steps: 
      - name: Setup Kubernetes
      	......
      - name: Checkout Code
        ......
      - name: Install Service Mesh and Deploy Application
        ......
      - name: Run Benchmark Tests
        ......

  stop-runner:
    name: Stop self-hosted runner
    needs:
      - start-runner # required to get output from the start-runner job
      - run-benchmarks # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure CNCF CIL credentials
      	......
      - name: Stop CNCF CIL runner
      	......
```
@leecalcote @navendu-pottekkat Do you have any comments on above workflow design?
